# Generated by Django 4.0.5 on 2022-07-13 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import volley.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('content', models.TextField(verbose_name='Текст статьи')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Картинка')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'статьи',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-time_create', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'категорию',
                'verbose_name_plural': 'Категория',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Тема')),
                ('content', models.TextField(verbose_name='Текст')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'Обратная связь',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Organizators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Имя/Фамилия')),
                ('content', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'организатора',
                'verbose_name_plural': 'Организаторы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Question_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(db_index=True, max_length=50, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'организатора',
                'verbose_name_plural': 'Вопросы/Ответы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=7, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'категорию',
                'verbose_name_plural': 'Категория',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название тура')),
                ('slug', models.SlugField(max_length=70, unique=True, verbose_name='Слаг')),
                ('picture', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Картинка')),
                ('content', models.TextField(verbose_name='Описание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('date', models.CharField(max_length=50, verbose_name='Дата проведения')),
                ('location', models.CharField(max_length=100, null=True, verbose_name='Локация')),
                ('event_format', models.CharField(max_length=100, null=True, verbose_name='Формат турнира')),
                ('money_prize', models.CharField(max_length=100, null=True, verbose_name='Призовой фонд')),
            ],
            options={
                'verbose_name': 'тур',
                'verbose_name_plural': 'Календарь',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TablePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(db_index=True, max_length=30, null=True, verbose_name='Название команды')),
                ('second_names', models.CharField(max_length=70, null=True, verbose_name='Фамилии игроков')),
                ('set_difference', models.CharField(max_length=10, null=True, verbose_name='Выигранные/Проигранные партии')),
                ('count_tours', models.CharField(max_length=2, null=True, verbose_name='Туров сыграно')),
                ('points', models.CharField(max_length=3, null=True, verbose_name='Очки')),
            ],
            options={
                'verbose_name': 'турнирную таблицу',
                'verbose_name_plural': 'Турнирная таблица',
                'ordering': ['-points'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title_photo', models.ImageField(null=True, upload_to='', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'фотографию',
                'verbose_name_plural': 'Фотогаллерея',
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Название трансляции')),
                ('refer', models.CharField(max_length=255, null=True, verbose_name='Ссылка  на трансляцию')),
                ('name_2', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Название трансляции #2')),
                ('refer_2', models.CharField(max_length=255, null=True, verbose_name='Ссылка  на трансляцию #2')),
                ('name_3', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Название трансляции #3')),
                ('refer_3', models.CharField(max_length=255, null=True, verbose_name='Ссылка  на трансляцию #3')),
                ('info', models.TextField(max_length=255, null=True, verbose_name='Информация о трансляции')),
                ('picture', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Картинка')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'трансляцию',
                'verbose_name_plural': 'Трансляция',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Имя игрока')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('content', models.TextField(null=True, verbose_name='Текст статьи')),
                ('height', models.CharField(max_length=6, verbose_name='Рост')),
                ('city', models.CharField(max_length=20, verbose_name='Город')),
                ('age', models.CharField(max_length=2, verbose_name='Возраст')),
                ('value', models.CharField(blank=True, max_length=30, verbose_name='Спортивное звание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('instagram', models.CharField(max_length=255, null=True, verbose_name='Инстаграм')),
                ('facebook', models.CharField(max_length=255, null=True, verbose_name='Фейсбук')),
                ('rank', models.CharField(max_length=100, null=True, verbose_name='Рейтинг игрока')),
                ('sex', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='volley.sex', verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'игрока',
                'verbose_name_plural': 'Игроки',
                'ordering': ['-rank', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=volley.models.upload_gallery_image)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volley.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания комментария')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('status', models.BooleanField(default=False, verbose_name='Видимость комментария')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_article', to='volley.article', verbose_name='Статья')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Эмейл')),
                ('body', models.TextField(verbose_name='Комментарий')),
                ('create_on', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('active', models.BooleanField(default=False, verbose_name='Активен/Неактивен')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='volley.article', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'Коментарии',
                'ordering': ['create_on'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='volley.category', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(db_index=True, max_length=30, verbose_name='Команда')),
                ('tour_category', models.CharField(db_index=True, max_length=30, verbose_name='Категория')),
                ('player_1', models.CharField(db_index=True, max_length=30, verbose_name='Игрок №1')),
                ('player_2', models.CharField(db_index=True, max_length=30, verbose_name='Игрок №2')),
                ('city', models.CharField(db_index=True, max_length=20, verbose_name='Город')),
                ('phone', models.CharField(db_index=True, max_length=12, verbose_name='Телефон')),
                ('rank', models.CharField(max_length=5, null=True, verbose_name='Рейтинг')),
                ('team_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='volley.tablepoints', verbose_name='ID команды')),
            ],
            options={
                'verbose_name': 'заявку',
                'verbose_name_plural': 'Заявка участника',
                'ordering': ['id'],
            },
        ),
    ]
